# Generated by Django 3.2.4 on 2021-06-24 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg. Notebook', max_length=128)),
                ('description', models.TextField(help_text='Tell the buyers something about your product')),
                ('price', models.FloatField(default=0, help_text='3.50')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(default='product_images/default.png', upload_to='product_images')),
                ('image2', models.ImageField(blank=True, upload_to='product_images')),
                ('image3', models.ImageField(blank=True, upload_to='product_images')),
                ('image4', models.ImageField(blank=True, upload_to='product_images')),
                ('image5', models.ImageField(blank=True, upload_to='product_images')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hawkuna.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('picture', models.ImageField(default='profile_images/default-user.png', upload_to='profile_images')),
                ('dob', models.DateField(null=True)),
                ('isSeller', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('paypal', models.BooleanField(default=False)),
                ('cash', models.BooleanField(default=False)),
                ('bank_transfer', models.BooleanField(default=False)),
                ('date_reg', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='hawkuna.CurrentProduct')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hawkuna.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hawkuna.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg. Notebook', max_length=128)),
                ('description', models.TextField(help_text='Tell the buyers something about your product')),
                ('price', models.FloatField(default=0, help_text='3.50')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(default='product_images/default.png', upload_to='product_images')),
                ('buyer', models.ForeignKey(on_delete=models.SET('This user no longer exists'), related_name='buyer', to='hawkuna.userprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hawkuna.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_by', to='hawkuna.userprofile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hawkuna.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insert title here', max_length=128)),
                ('text', models.TextField(help_text='Tell us how the seller was')),
                ('on_date', models.DateField(auto_now_add=True, null=True)),
                ('rating', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='hawkuna.userprofile')),
                ('product', models.OneToOneField(on_delete=models.SET('This product no longer exists'), to='hawkuna.soldproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='hawkuna.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Type your message here')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hawkuna.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hawkuna.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='currentproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='hawkuna.userprofile'),
        ),
        migrations.AddField(
            model_name='currentproduct',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hawkuna.subcategory'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='hawkuna.userprofile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='hawkuna.userprofile'),
        ),
    ]
